import type { CssArtComponent } from './components/css-art/index';
import {
  ElementFireCssIcon,
  ElementWindCssIcon,
  ElementWaterCssIcon,
  FilmGalleryCssIcon,
  HomeConwayGameBanner,
  HomeEdwinDashboardBanner,
  HomeFilmGalleryBanner,
  HomeBaguaMirrorTotem,
  HomeGramophoneTotem,
  HomeJijuDiscoveryBanner,
  HomeLifeDatasetBanner,
  HomeLifeMagicIcon,
  HomePowerUpTotem,
  HomeProjectsBlueprintIcon,
  IGamingChipsBanner,
  IGamingFishingArt,
  IGamingLiveArt,
  IGamingLotteryArt,
  IGamingRngArt,
  IGamingSlotsArt,
  IGamingSportsArt,
  IGamingLedgerBanner,
  IGamingGearsBanner,
  IGamingCompassBanner,
  IGamingHeroPlateArt,
  IGamingSealArt,
  IGamingLoopBanner,
  IGamingTableBanner,
  MathFractalRuneCssIcon,
  MathIntegralSpellCssIcon,
  MathMatrixPortalCssIcon,
  MathPiOrbCssIcon,
  MathPrimeSigilCssIcon,
  MathVectorGateCssIcon,
  PenneyCoinCssIcon,
  OfficeCalendarCssIcon,
  OfficeContractCssIcon,
  OfficeInboxCssIcon,
  OfficeReportCssIcon,
  OfficeTeamBoardCssIcon,
  OfficeWorkflowCssIcon,
  ProjectsCrmCssIcon,
  ProjectsDrRacingCssIcon,
  ProjectsEtReportCssIcon,
  ProjectsJijuCssIcon,
  ProjectsLifeOsCssIcon,
  ProjectsMiyaCssIcon,
  ProjectsPokerCssIcon,
  WikiBackgroundMusicCssIcon,
  WikiButtonFeedbackCssIcon,
  WikiFirebaseStorageCssIcon,
  WikiRagFlowCssIcon,
  WikiSkillsCssIcon,
  WikiViteCssIcon,
} from './components/css-art/index';

export type LocalizedText = {
  en: string;
  zh: string;
};

export type CssArtCategory =
  | 'project-icon'
  | 'home-selected-work-banner'
  | 'home-system'
  | 'home-interest'
  | 'office-icon'
  | 'math-magic-icon'
  | 'elemental-icon'
  | 'wiki-icon'
  | 'engraved-banner';
export type CssArtBackground = 'framed' | 'transparent' | 'scene';
export type CssArtRatio = '1:1' | 'banner' | 'transparent-totem';

export type CssArtRegistryItem = {
  id: string;
  title: string;
  projectTitle?: string;
  category: CssArtCategory;
  sourceRoute: string;
  ratio: CssArtRatio;
  background: CssArtBackground;
  supportsDarkMode: boolean;
  supportsReducedMotion: boolean;
  cssFile: string;
  Component: CssArtComponent;
  label: LocalizedText;
  copy: LocalizedText;
};

export const cssArtRegistry: readonly CssArtRegistryItem[] = [
  {
    id: 'projects-jiju',
    title: 'Jiju',
    projectTitle: 'Jiju',
    category: 'project-icon',
    sourceRoute: '/projects',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsJijuCssIcon,
    label: {
      en: 'Jiju CSS app icon',
      zh: 'Jiju CSS app 图标',
    },
    copy: {
      en: 'The framed cat-scene app icon used by the Jiju project card.',
      zh: 'Jiju project card 使用的固定底猫场景 app icon。',
    },
  },
  {
    id: 'projects-friday-poker-club',
    title: 'Friday Poker Club',
    projectTitle: 'Friday Poker Club',
    category: 'project-icon',
    sourceRoute: '/projects',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsPokerCssIcon,
    label: {
      en: 'Friday Poker Club CSS app icon',
      zh: 'Friday Poker Club CSS app 图标',
    },
    copy: {
      en: 'The framed table-and-pocket-aces icon used by the poker project card.',
      zh: 'Friday Poker Club project card 使用的固定底牌桌和对 A app icon。',
    },
  },
  {
    id: 'projects-dr-racing',
    title: 'Dr Racing',
    projectTitle: 'Dr Racing',
    category: 'project-icon',
    sourceRoute: '/projects',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsDrRacingCssIcon,
    label: {
      en: 'Dr Racing dashboard CSS app icon',
      zh: 'Dr Racing 仪表台 CSS app 图标',
    },
    copy: {
      en: 'The framed rev-counter icon with a sweeping needle and speed lines.',
      zh: 'Dr Racing 使用的固定底转速表 app icon，包含摆动指针与速度线。',
    },
  },
  {
    id: 'projects-etreporthub',
    title: 'ETReportHub',
    projectTitle: 'ETReportHub',
    category: 'project-icon',
    sourceRoute: '/projects',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsEtReportCssIcon,
    label: {
      en: 'ETReportHub data CSS app icon',
      zh: 'ETReportHub 数据 CSS app 图标',
    },
    copy: {
      en: 'The framed data-dashboard icon with animated bars and scan line.',
      zh: 'ETReportHub 使用的固定底数据仪表盘 app icon，包含动态 bar 和 scan line。',
    },
  },
  {
    id: 'projects-life-os',
    title: 'Life OS',
    projectTitle: 'Life OS',
    category: 'project-icon',
    sourceRoute: '/projects',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsLifeOsCssIcon,
    label: {
      en: 'Life OS engraved eye CSS app icon',
      zh: 'Life OS 凹版之眼 CSS app 图标',
    },
    copy: {
      en: 'Matches the real Life OS app icon: ink-green plate, bronze-gold rules, guilloché rosette and radial burst, with an engraved eye on the double-ruled seal.',
      zh: '与 Life OS 真实 app 图标同款：墨绿印版、古铜金线、扭索纹玫瑰与放射细线，双线圆章中央一只凹版之眼。',
    },
  },
  {
    id: 'projects-miya',
    title: 'MiYa',
    projectTitle: 'MiYa',
    category: 'project-icon',
    sourceRoute: '/projects',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsMiyaCssIcon,
    label: {
      en: 'MiYa heart CSS app icon',
      zh: 'MiYa 心形 CSS app 图标',
    },
    copy: {
      en: 'The framed red heart icon for MiYa, the on-device iOS health report; the heart beats once per cycle.',
      zh: 'MiYa（本机 iOS 健康报告）使用的固定底红色心形 app icon，心形按节拍跳动。',
    },
  },
  {
    id: 'projects-crm-intelligence-system',
    title: 'CRM Intelligence System',
    projectTitle: 'CRM Intelligence System',
    category: 'project-icon',
    sourceRoute: '/projects',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsCrmCssIcon,
    label: {
      en: 'CRM Intelligence System magic circle CSS app icon',
      zh: 'CRM Intelligence System 魔法阵 CSS app 图标',
    },
    copy: {
      en: 'The framed magic-circle system icon used by the CRM project card.',
      zh: 'CRM project card 使用的固定底魔法阵系统 app icon。',
    },
  },
  {
    id: 'home-selected-work-edwin-dashboard',
    title: 'Edwin Dashboard',
    projectTitle: 'Edwin Dashboard',
    category: 'home-selected-work-banner',
    sourceRoute: '/',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-selected-work-banners.css',
    Component: HomeEdwinDashboardBanner,
    label: {
      en: 'Edwin Dashboard decision system CSS banner',
      zh: 'Edwin Dashboard 决策系统 CSS banner',
    },
    copy: {
      en: 'A dashboard window with KPI cards, bars, a trend line, and one highlighted decision signal.',
      zh: '包含 KPI 卡、柱状图、趋势线与重点决策信号的 dashboard 视窗。',
    },
  },
  {
    id: 'home-selected-work-jiju',
    title: 'Jiju',
    projectTitle: 'Jiju',
    category: 'home-selected-work-banner',
    sourceRoute: '/',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-selected-work-banners.css',
    Component: HomeJijuDiscoveryBanner,
    label: {
      en: 'Jiju local discovery CSS banner',
      zh: 'Jiju 本地发现 CSS banner',
    },
    copy: {
      en: 'A pet-friendly map route with place pins, a moving traveler, and a verified pet profile card.',
      zh: '包含地点 pin、移动路线与已验证宠物资料卡的宠物友好发现地图。',
    },
  },
  {
    id: 'home-selected-work-life-as-a-dataset',
    title: 'Life as a Dataset',
    projectTitle: 'Life as a Dataset',
    category: 'home-selected-work-banner',
    sourceRoute: '/',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-selected-work-banners.css',
    Component: HomeLifeDatasetBanner,
    label: {
      en: 'Life as a Dataset timeline CSS banner',
      zh: 'Life as a Dataset 人生时间轴 CSS banner',
    },
    copy: {
      en: 'A personal-data timeline with journal cards, changing nodes, and a recurring orbit.',
      zh: '由记录卡、变化节点与循环轨迹组成的个人数据时间轴。',
    },
  },
  {
    id: 'home-conway-game-banner',
    title: "Conway's Game of Life",
    projectTitle: "Conway's Game of Life",
    category: 'home-selected-work-banner',
    sourceRoute: '/',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-conway-banner.css',
    Component: HomeConwayGameBanner,
    label: {
      en: "Conway's Game of Life cellular automata CSS banner",
      zh: "Conway's Game of Life 细胞自动机 CSS banner",
    },
    copy: {
      en: 'A 16:9 cellular board with living cells, a glider, and the magic-circle language from the Conway app icon.',
      zh: '16:9 生命棋盘、活细胞与 glider，并延续 Conway app icon 的魔法阵视觉语言。',
    },
  },
  {
    id: 'home-film-gallery-banner',
    title: 'Film Gallery',
    projectTitle: 'Film Gallery',
    category: 'home-selected-work-banner',
    sourceRoute: '/',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/film-gallery-icon.css',
    Component: HomeFilmGalleryBanner,
    label: {
      en: 'Film Gallery moving film strip CSS banner',
      zh: 'Film Gallery 横向移动胶卷 CSS banner',
    },
    copy: {
      en: 'A 16:9 film strip with perforations, three framed scenes, twin reels, and restrained left-to-right motion.',
      zh: '16:9 胶卷、齿孔、三格取景、双卷轴与克制的横向移动动效。',
    },
  },
  {
    id: 'home-projects-hub-blueprint',
    title: 'Projects Hub',
    category: 'home-system',
    sourceRoute: '/',
    ratio: '1:1',
    background: 'transparent',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-projects-blueprint.css',
    Component: HomeProjectsBlueprintIcon,
    label: {
      en: 'Projects Hub blueprint CSS icon',
      zh: 'Projects Hub 设计图纸 CSS 图标',
    },
    copy: {
      en: 'The transparent blueprint icon from the Home System Files section.',
      zh: '主页 System Files 区块里的透明底设计图纸 CSS 图标。',
    },
  },
  {
    id: 'home-life-os-magic',
    title: 'Life OS RPG System',
    category: 'home-system',
    sourceRoute: '/',
    ratio: '1:1',
    background: 'transparent',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-life-magic.css',
    Component: HomeLifeMagicIcon,
    label: {
      en: 'Life OS engraved heartbeat seal CSS icon',
      zh: 'Life OS 凹版心跳印章 CSS 图标',
    },
    copy: {
      en: 'Banknote-intaglio seal matching the Life OS app icon: radial burst, guilloché rosette and a φ tick ring around an engraved heartbeat that beats in foil.',
      zh: '与 Life OS app 图标同款的凹版印章：放射细线、扭索纹玫瑰与 φ 刻度环，中间一条凹版心跳线按节拍泛出金箔。',
    },
  },
  {
    id: 'home-life-os-power-up',
    title: 'Life OS',
    category: 'home-interest',
    sourceRoute: '/',
    ratio: 'transparent-totem',
    background: 'transparent',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-interest-totems.css',
    Component: HomePowerUpTotem,
    label: {
      en: 'Life OS engraved pole-star transparent CSS totem',
      zh: 'Life OS 凹版北极星透明底 CSS 图腾',
    },
    copy: {
      en: 'Transparent intaglio totem for the Home Interests Life OS card: a twelve-palace tick ring and guilloché band around a foil pole star. Engraved pieces draw no people, so the old power-up figure was retired.',
      zh: '主页 Interests 里 Life OS 的透明底凹版图腾：十二宫刻度环与扭索纹环围着一颗金箔北极星。凹版语言不画人，原来的变身小人已退役。',
    },
  },
  {
    id: 'home-analog-tech-gramophone',
    title: 'Analog Tech',
    category: 'home-interest',
    sourceRoute: '/',
    ratio: 'transparent-totem',
    background: 'transparent',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-interest-totems.css',
    Component: HomeGramophoneTotem,
    label: {
      en: 'Analog Tech vibrating gramophone transparent CSS totem',
      zh: 'Analog Tech 留声机振动透明底 CSS 图腾',
    },
    copy: {
      en: 'The transparent classic gramophone totem used by the Home Interests Analog Tech card.',
      zh: '主页 Interests 里 Analog Tech 使用的经典留声机透明底图腾。',
    },
  },
  {
    id: 'home-film-gallery-app-icon',
    title: 'Film Gallery',
    category: 'home-interest',
    sourceRoute: '/',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/film-gallery-icon.css',
    Component: FilmGalleryCssIcon,
    label: {
      en: 'Film Gallery rounded-square CSS app icon',
      zh: 'Film Gallery 圆角正方形 CSS app 图标',
    },
    copy: {
      en: 'A framed film-strip app icon used by the Home Humans & Systems shelf.',
      zh: '主页 Humans & Systems 货架使用的固定底胶片卷轴 app 图标。',
    },
  },
  {
    id: 'home-pattern-archive-bagua',
    title: 'Pattern Archive',
    category: 'home-interest',
    sourceRoute: '/',
    ratio: 'transparent-totem',
    background: 'transparent',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/home-interest-totems.css',
    Component: HomeBaguaMirrorTotem,
    label: {
      en: 'Pattern Archive transparent Bagua mirror CSS totem',
      zh: 'Pattern Archive 道教八卦镜透明底 CSS 图腾',
    },
    copy: {
      en: 'The transparent Bagua mirror totem used by the Home Interests Pattern Archive card.',
      zh: '主页 Interests 里 Pattern Archive 使用的透明底八卦镜图腾。',
    },
  },
  {
    id: 'penney-coin-hustle',
    title: "Penney's Game",
    category: 'project-icon',
    sourceRoute: '/penneys-game',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/penney-coins.css',
    Component: PenneyCoinCssIcon,
    label: {
      en: "Penney's Game coin CSS app icon",
      zh: "Penney's Game 硬币 CSS app 图标",
    },
    copy: {
      en: 'Two offset coins inside a rotating non-transitive arc, used by the /penneys-game hero and the Projects app shelf.',
      zh: '两枚错位硬币加一道旋转的非传递弧线，用于 /penneys-game 页面 hero 与 Projects app 货架。',
    },
  },
  {
    id: 'home-conway-magic-circle',
    title: "Conway's Game of Life",
    category: 'home-interest',
    sourceRoute: '/',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/projects-icons.css',
    Component: ProjectsCrmCssIcon,
    label: {
      en: "Conway's Game of Life magic-circle CSS app icon",
      zh: "Conway's Game of Life 魔法阵 CSS app 图标",
    },
    copy: {
      en: "The framed magic-circle app icon used by the Conway page and the Home Humans & Systems shelf.",
      zh: "Conway 页面与主页 Humans & Systems 货架使用的固定底魔法阵 app 图标。",
    },
  },
  {
    id: 'office-desk-calendar',
    title: 'Desk Calendar',
    category: 'office-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/office-icons.css',
    Component: OfficeCalendarCssIcon,
    label: {
      en: 'Desk Calendar framed CSS app icon',
      zh: 'Desk Calendar 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'An emoji-like planning icon with a large calendar page and faint date dots.',
      zh: '偏 emoji 风格的计划排程图标：大日历页和若隐若现的日期点。',
    },
  },
  {
    id: 'office-inbox-tray',
    title: 'Inbox Tray',
    category: 'office-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/office-icons.css',
    Component: OfficeInboxCssIcon,
    label: {
      en: 'Inbox Tray framed CSS app icon',
      zh: 'Inbox Tray 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'An emoji-like document intake icon with large papers, tray, and no text lines.',
      zh: '偏 emoji 风格的文件流入图标：大纸张、托盘，不放横线文字。',
    },
  },
  {
    id: 'office-report-sheet',
    title: 'Report Sheet',
    category: 'office-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/office-icons.css',
    Component: OfficeReportCssIcon,
    label: {
      en: 'Report Sheet framed CSS app icon',
      zh: 'Report Sheet 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'An emoji-like reporting icon with a big sheet, simple bars, and check mark.',
      zh: '偏 emoji 风格的报表图标：大文件、简单 bar 和 check mark。',
    },
  },
  {
    id: 'office-team-board',
    title: 'Team Board',
    category: 'office-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/office-icons.css',
    Component: OfficeTeamBoardCssIcon,
    label: {
      en: 'Team Board framed CSS app icon',
      zh: 'Team Board 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'An emoji-like team board icon with simple cards that flip.',
      zh: '偏 emoji 风格的团队看板图标：简单卡片翻卡。',
    },
  },
  {
    id: 'office-contract-seal',
    title: 'Contract Seal',
    category: 'office-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/office-icons.css',
    Component: OfficeContractCssIcon,
    label: {
      en: 'Contract Seal framed CSS app icon',
      zh: 'Contract Seal 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'An emoji-like signing icon with a big paper, pen, triangle mark, and seal.',
      zh: '偏 emoji 风格的签署图标：大文件、笔、三角形记号和印章。',
    },
  },
  {
    id: 'office-workflow-automator',
    title: 'Workflow Automator',
    category: 'office-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/office-icons.css',
    Component: OfficeWorkflowCssIcon,
    label: {
      en: 'Workflow Automator framed CSS app icon',
      zh: 'Workflow Automator 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'An emoji-like automation icon with a magic wand lighting up workflow nodes.',
      zh: '偏 emoji 风格的自动化图标：魔法棒点亮流程节点。',
    },
  },
  {
    id: 'math-prime-sigil',
    title: 'Prime Sigil',
    category: 'math-magic-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/math-magic-icons.css',
    Component: MathPrimeSigilCssIcon,
    label: {
      en: 'Prime Sigil framed CSS app icon',
      zh: 'Prime Sigil 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'A spellbook-style icon: a prime number glowing inside a rotating sigil.',
      zh: '魔法书风格 icon：质数在旋转符文阵里发光。',
    },
  },
  {
    id: 'math-vector-gate',
    title: 'Vector Gate',
    category: 'math-magic-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/math-magic-icons.css',
    Component: MathVectorGateCssIcon,
    label: {
      en: 'Vector Gate framed CSS app icon',
      zh: 'Vector Gate 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'A vector spell gate with casting arrows, aura rings, and portal glow.',
      zh: '向量施法门：箭头、光环轨道和传送门一起发光。',
    },
  },
  {
    id: 'math-integral-spell',
    title: 'Integral Spell',
    category: 'math-magic-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/math-magic-icons.css',
    Component: MathIntegralSpellCssIcon,
    label: {
      en: 'Integral Spell framed CSS app icon',
      zh: 'Integral Spell 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'A calculus spell icon with a floating integral mark and glowing magic area.',
      zh: '微积分咒式 icon：漂浮积分符号和发光魔法面积。',
    },
  },
  {
    id: 'math-pi-orb',
    title: 'Pi Orb',
    category: 'math-magic-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/math-magic-icons.css',
    Component: MathPiOrbCssIcon,
    label: {
      en: 'Pi Orb framed CSS app icon',
      zh: 'Pi Orb 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'A pi orb artifact with orbiting moons and a slow arcane pulse.',
      zh: 'π 球体法器：小月点环绕，慢速奥术脉冲。',
    },
  },
  {
    id: 'math-fractal-rune',
    title: 'Fractal Rune',
    category: 'math-magic-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/math-magic-icons.css',
    Component: MathFractalRuneCssIcon,
    label: {
      en: 'Fractal Rune framed CSS app icon',
      zh: 'Fractal Rune 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'A recursive rune tree with luminous branches and spell nodes.',
      zh: '递归符文树：发光枝条和咒式节点。',
    },
  },
  {
    id: 'math-matrix-portal',
    title: 'Matrix Portal',
    category: 'math-magic-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/math-magic-icons.css',
    Component: MathMatrixPortalCssIcon,
    label: {
      en: 'Matrix Portal framed CSS app icon',
      zh: 'Matrix Portal 1:1 framed CSS app 图标',
    },
    copy: {
      en: 'A matrix portal spell with bracket glyphs, blinking cells, and a bright core.',
      zh: '矩阵传送咒：括号符印、闪烁单元和发光核心。',
    },
  },
  {
    id: 'element-fire',
    title: 'Fire Element',
    category: 'elemental-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/elemental-icons.css',
    Component: ElementFireCssIcon,
    label: {
      en: 'Fire Element 1:1 CSS icon',
      zh: 'Fire Element 1:1 CSS 图标',
    },
    copy: {
      en: 'A flatter framed fire-element icon with a bold flame, embers, and a slow lava base glow.',
      zh: '更 flat 的火元素 framed icon：大块火焰、灰烬火星和慢速熔岩底光。',
    },
  },
  {
    id: 'element-water',
    title: 'Water Element',
    category: 'elemental-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/elemental-icons.css',
    Component: ElementWaterCssIcon,
    label: {
      en: 'Water Element 1:1 CSS icon',
      zh: 'Water Element 1:1 CSS 图标',
    },
    copy: {
      en: 'A flat framed water-element icon with a clear droplet shape, bubbles, and a slow tide glow.',
      zh: 'flat 水元素 framed icon：清楚的水滴轮廓、气泡和慢速潮汐底光。',
    },
  },
  {
    id: 'element-wind',
    title: 'Wind Element',
    category: 'elemental-icon',
    sourceRoute: '/project-css',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/elemental-icons.css',
    Component: ElementWindCssIcon,
    label: {
      en: 'Wind Element 1:1 CSS icon',
      zh: 'Wind Element 1:1 CSS 图标',
    },
    copy: {
      en: 'A flat framed wind-element icon with soft gust bands, small leaves, and a slow breeze glow.',
      zh: 'flat 风元素 framed icon：柔和风带、小叶片和慢速微风底光。',
    },
  },
  {
    id: 'wiki-vite',
    title: 'Vite Skill',
    category: 'wiki-icon',
    sourceRoute: '/wiki/vite',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/wiki-icons.css',
    Component: WikiViteCssIcon,
    label: {
      en: 'Vite skill CSS icon',
      zh: 'Vite skill CSS 图标',
    },
    copy: {
      en: 'A compact framed lightning-and-build icon for the Vite wiki card.',
      zh: '小型 framed lightning/build CSS icon，用于 Vite wiki card。',
    },
  },
  {
    id: 'wiki-background-music',
    title: 'Background Music',
    category: 'wiki-icon',
    sourceRoute: '/wiki/background-music',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/wiki-icons.css',
    Component: WikiBackgroundMusicCssIcon,
    label: {
      en: 'Background music CSS icon',
      zh: 'Background music CSS 图标',
    },
    copy: {
      en: 'A compact framed record-and-sound icon for the background music wiki card.',
      zh: '小型 framed record/sound CSS icon，用于 background music wiki card。',
    },
  },
  {
    id: 'wiki-button-feedback',
    title: 'Button Feedback',
    category: 'wiki-icon',
    sourceRoute: '/wiki/button-feedback',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/wiki-icons.css',
    Component: WikiButtonFeedbackCssIcon,
    label: {
      en: 'Button feedback CSS icon',
      zh: 'Button feedback CSS 图标',
    },
    copy: {
      en: 'A compact framed press-and-signal icon for the button feedback wiki card.',
      zh: '小型 framed press/signal CSS icon，用于 button feedback wiki card。',
    },
  },
  {
    id: 'wiki-firebase-storage',
    title: 'Firebase Lifetime Storage',
    category: 'wiki-icon',
    sourceRoute: '/wiki/firebase-lifetime-storage',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/wiki-icons.css',
    Component: WikiFirebaseStorageCssIcon,
    label: {
      en: 'Firebase lifetime storage CSS icon',
      zh: 'Firebase lifetime storage CSS 图标',
    },
    copy: {
      en: 'A compact framed storage-and-spark icon for the Firebase lifetime storage wiki card.',
      zh: '小型 framed storage/spark CSS icon，用于 Firebase lifetime storage wiki card。',
    },
  },
  {
    id: 'wiki-skills',
    title: 'Reusable Skills',
    category: 'wiki-icon',
    sourceRoute: '/wiki/skills',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/wiki-icons.css',
    Component: WikiSkillsCssIcon,
    label: {
      en: 'Reusable skills CSS icon',
      zh: 'Reusable skills CSS 图标',
    },
    copy: {
      en: 'A compact framed multi-card icon for the reusable skills wiki card.',
      zh: '小型 framed multi-card CSS icon，用于 reusable skills wiki card。',
    },
  },
  {
    id: 'wiki-rag-flow',
    title: 'Tag Registry and RAG Flow',
    category: 'wiki-icon',
    sourceRoute: '/wiki/rag-flow',
    ratio: '1:1',
    background: 'framed',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/wiki-icons.css',
    Component: WikiRagFlowCssIcon,
    label: {
      en: 'Tag Registry and RAG flow CSS icon',
      zh: 'Tag Registry 与 RAG flow CSS 图标',
    },
    copy: {
      en: 'A compact framed note-and-tag icon with simple object motion for the RAG flow page.',
      zh: '小型 framed note/tag CSS icon，用简单实体物件动效表达 RAG flow。',
    },
  },
  {
    id: 'igaming-table',
    title: 'iGaming · The table',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingTableBanner,
    label: {
      en: 'Engraved roulette wheel banner',
      zh: '凹版轮盘 banner',
    },
    copy: {
      en: 'Starter-pack banner: a 37-pocket wheel (one foil zero, 18 pairs) on the golden point, ringed by φ ticks and guilloché.',
      zh: '入门包 banner：37 格轮盘（一格金箔零位 + 18 对）落在黄金点上，外面是 φ 刻度环和扭索纹。',
    },
  },
  {
    id: 'igaming-chips',
    title: 'iGaming · Promotions',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingChipsBanner,
    label: {
      en: 'Engraved casino chips banner',
      zh: '凹版筹码 banner',
    },
    copy: {
      en: 'Promotions banner: an edge-inserted chip with a guilloché face; satellite chips shrink by φ (22 → 13.6 → 8.4 → 5.2).',
      zh: '促销 banner：带边缘刻齿与扭索纹面的筹码，周围小筹码按 φ 递减（22 → 13.6 → 8.4 → 5.2）。',
    },
  },
  {
    id: 'igaming-loop',
    title: 'iGaming · Workflow',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingLoopBanner,
    label: {
      en: 'Engraved infinity loop banner',
      zh: '凹版无限循环 banner',
    },
    copy: {
      en: 'Workflow banner: a lemniscate of two hatched loops meeting at the golden point, with a foil runner on each loop.',
      zh: '工作流程 banner：两个排线圆环在黄金点相交成双纽线，每个环上有一颗金箔标记在走。',
    },
  },
  {
    id: 'igaming-ledger',
    title: 'iGaming · Reporting',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingLedgerBanner,
    label: {
      en: 'Engraved Fibonacci ledger banner',
      zh: '凹版斐波那契账本 banner',
    },
    copy: {
      en: 'Reporting banner: bars in Fibonacci proportion (3·5·8·13·21) inside a golden rectangle, hatching deepening with height, and a foil trend line.',
      zh: '报表 banner：黄金矩形里按斐波那契比例（3·5·8·13·21）排列的柱子，越高排线越密，外加一条金箔趋势线。',
    },
  },
  {
    id: 'igaming-gears',
    title: 'iGaming · B2B',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingGearsBanner,
    label: {
      en: 'Engraved meshing gears banner',
      zh: '凹版咬合齿轮 banner',
    },
    copy: {
      en: 'B2B banner: a 21-tooth and a 13-tooth gear (Fibonacci neighbours, sized by φ) meshing on the golden point, turning at the matching 13:21 speed ratio.',
      zh: 'B2B banner：21 齿与 13 齿两个齿轮（斐波那契相邻数，大小按 φ）在黄金点咬合，转速按 13:21 配比。',
    },
  },
  {
    id: 'igaming-compass',
    title: 'iGaming · Troubleshooting',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingCompassBanner,
    label: {
      en: 'Engraved compass rose banner',
      zh: '凹版罗盘 banner',
    },
    copy: {
      en: 'Troubleshooting banner: an eight-point rose with half-hatched points inside a 32-point dial; the foil needle swings, searches, then settles on north.',
      zh: '排查 banner：32 分度刻盘里的八角罗盘玫瑰，每个尖角半边排线；金箔指针来回摆动寻找，最后停在北方。',
    },
  },
  {
    id: 'igaming-hero-plate',
    title: 'iGaming · Hero plate',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingHeroPlateArt,
    label: {
      en: 'Engraved banknote plate behind the iGaming hero',
      zh: 'iGaming 首屏背后的凹版钞票版面',
    },
    copy: {
      en: 'Hero plate: rice-paper face with a double frame, guilloché bands and corner rosettes; rays, rosette and two φ rings (23.6 → 38.2) centre on the upper golden point, leaving the headline on clean paper.',
      zh: '首屏版面：米纸底、双线框、上下扭索纹带与四角小玫瑰；放射线、扭索纹玫瑰和两圈 φ 刻度环（23.6 → 38.2）都以上方黄金点为圆心，中间留白给标题。',
    },
  },
  {
    id: 'igaming-seal',
    title: 'iGaming · Seal',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: '1:1',
    background: 'transparent',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingSealArt,
    label: {
      en: 'Engraved guilloché seal with a foil star',
      zh: '带金箔星芒的凹版扭索纹印章',
    },
    copy: {
      en: 'Closing mark: a transparent medallion — 48-tick rim, guilloché ring, foil eight-point star — set above the page’s last word.',
      zh: '结尾印记：透明底的圆章——48 格刻度边、扭索纹环、金箔八角星，放在整页最后一段上方。',
    },
  },
  {
    id: 'igaming-floor-slots',
    title: 'iGaming floor · Slots',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingSlotsArt,
    label: {
      en: 'Engraved slot machine with three spinning reels',
      zh: '三条滚轴转动的凹版老虎机',
    },
    copy: {
      en: 'Three reels scroll a coin and bar strip behind a foil payline.',
      zh: '三条滚轴滚动硬币与横杠图案，中间一条金箔中奖线。',
    },
  },
  {
    id: 'igaming-floor-live',
    title: 'iGaming floor · Live casino',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingLiveArt,
    label: {
      en: 'Engraved playing cards dealt onto a table edge',
      zh: '发到桌边的凹版扑克牌',
    },
    copy: {
      en: 'A cross-hatched card back and a foil-pip face card that is dealt in on a loop.',
      zh: '一张交叉排线的牌背，一张金箔花色的牌面反复发入。',
    },
  },
  {
    id: 'igaming-floor-rng',
    title: 'iGaming floor · RNG table',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingRngArt,
    label: {
      en: 'Engraved dice tumbling',
      zh: '翻滚的凹版骰子',
    },
    copy: {
      en: 'Two engraved dice tumbling on offset clocks.',
      zh: '两颗凹版骰子错开节奏翻滚。',
    },
  },
  {
    id: 'igaming-floor-sports',
    title: 'iGaming floor · Sportsbook',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingSportsArt,
    label: {
      en: 'Engraved football bouncing on a pitch line',
      zh: '在球场中线上弹跳的凹版足球',
    },
    copy: {
      en: 'A panelled ball bounces on the halfway line with a hatched shadow.',
      zh: '拼块足球在中线上弹跳，下方一道排线影子。',
    },
  },
  {
    id: 'igaming-floor-fishing',
    title: 'iGaming floor · Fishing and arcade',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingFishingArt,
    label: {
      en: 'Engraved fish swimming through a reticle',
      zh: '游过准星的凹版鱼群',
    },
    copy: {
      en: 'Hatched fish swim right to left through a pulsing foil reticle.',
      zh: '排线鱼群从右往左游过一个一张一缩的金箔准星。',
    },
  },
  {
    id: 'igaming-floor-lottery',
    title: 'iGaming floor · Lottery and fast games',
    category: 'engraved-banner',
    sourceRoute: '/igaming',
    ratio: 'banner',
    background: 'scene',
    supportsDarkMode: true,
    supportsReducedMotion: true,
    cssFile: 'styles/css-art/engraved-line.css',
    Component: IGamingLotteryArt,
    label: {
      en: 'Engraved lottery balls and a crash curve',
      zh: '凹版彩票球与 crash 曲线',
    },
    copy: {
      en: 'Four draw balls pop out in sequence in front of a climbing crash curve.',
      zh: '四颗号码球依次弹出，背后一条冲高的 crash 曲线。',
    },
  },
];

export const projectCssArtItems = cssArtRegistry.filter((item) => item.category === 'project-icon');
export const homeSelectedWorkBannerItems = cssArtRegistry.filter((item) => item.category === 'home-selected-work-banner');
export const homeSystemCssArtItems = cssArtRegistry.filter((item) => item.category === 'home-system');
export const homeInterestCssArtItems = cssArtRegistry.filter((item) => item.category === 'home-interest');
export const officeIconCssArtItems = cssArtRegistry.filter((item) => item.category === 'office-icon');
export const mathMagicIconCssArtItems = cssArtRegistry.filter((item) => item.category === 'math-magic-icon');
export const elementalIconCssArtItems = cssArtRegistry.filter((item) => item.category === 'elemental-icon');
export const wikiIconCssArtItems = cssArtRegistry.filter((item) => item.category === 'wiki-icon');

export const getProjectCssArtByProjectTitle = (projectTitle: string): CssArtRegistryItem | undefined =>
  projectCssArtItems.find((item) => item.projectTitle === projectTitle);

export const getHomeSelectedWorkBannerByTitle = (projectTitle: string): CssArtRegistryItem | undefined =>
  homeSelectedWorkBannerItems.find((item) => item.projectTitle === projectTitle);
